import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Any

import psycopg2
import psycopg2.extras

# Supabase Postgres 上の専用スキーマ。別アプリと混ざらないよう pokesleep に隔離する。
SCHEMA = "pokesleep"

MASTER_PATH = Path(__file__).parent / "data" / "pokemon_master.json"
BERRY_PATH = Path(__file__).parent / "data" / "berry.json"
INGREDIENT_PATH = Path(__file__).parent / "data" / "ingredient.json"
FIELD_PATH = Path(__file__).parent / "data" / "field.json"
RECIPE_PATH = Path(__file__).parent / "data" / "recipe.json"
MAIN_SKILL_PATH = Path(__file__).parent / "data" / "main_skill.json"
SUBSKILL_PATH = Path(__file__).parent / "data" / "subskill.json"
EVOLUTION_PATH = Path(__file__).parent / "data" / "evolution.json"
NATURE_PATH = Path(__file__).parent / "data" / "nature.json"
EVOLUTION_ITEM_PATH = Path(__file__).parent / "data" / "evolution_item.json"
SLEEP_RIBBON_PATH = Path(__file__).parent / "data" / "sleep_ribbon.json"

# SQLite の CURRENT_TIMESTAMP 互換の文字列（UTC・'YYYY-MM-DD HH:MM:SS'）を返す式。
# 既存ビューが created_at / updated_at を文字列スライスで使うため TEXT 型で揃える。
_NOW_SQL = "to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')"


# ---------- 接続まわり ----------

def _get_db_url() -> str:
    """接続文字列を取得する。優先順: 環境変数 → Streamlit secrets。"""
    url = os.environ.get("POKESLEEP_DB_URL") or os.environ.get("DB_URL")
    if not url:
        try:
            import streamlit as st

            url = st.secrets["DB_URL"]
        except Exception:
            url = None
    if not url:
        raise RuntimeError(
            "DB_URL が未設定です。ローカルなら .streamlit/secrets.toml に、"
            "Streamlit Cloud なら App settings → Secrets に DB_URL を設定してください。"
        )
    return str(url)


_conn = None


def get_connection():
    """psycopg2 接続を返す。プロセス内で使い回し、切れていたら張り直す。"""
    global _conn
    if _conn is None or _conn.closed:
        _conn = psycopg2.connect(_get_db_url(), options=f"-c search_path={SCHEMA}")
    return _conn


def _run(fn):
    """カーソルを開いて fn(cur) を実行し、コミットして結果を返す。

    接続が切れていた場合は一度だけ張り直してリトライする。
    """
    global _conn
    last_err: Exception | None = None
    for attempt in (1, 2):
        conn = get_connection()
        try:
            with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
                result = fn(cur)
            conn.commit()
            return result
        except (psycopg2.OperationalError, psycopg2.InterfaceError) as e:
            last_err = e
            try:
                conn.close()
            except Exception:
                pass
            _conn = None
        except psycopg2.Error:
            conn.rollback()
            raise
    raise last_err  # type: ignore[misc]


def _fetchall(sql: str, params: tuple = ()) -> list[dict[str, Any]]:
    def f(cur):
        cur.execute(sql, params)
        return cur.fetchall()

    return _run(f)


def _fetchone(sql: str, params: tuple = ()) -> dict[str, Any] | None:
    def f(cur):
        cur.execute(sql, params)
        return cur.fetchone()

    return _run(f)


def _execute(sql: str, params: tuple = (), returning: bool = False):
    def f(cur):
        cur.execute(sql, params)
        return cur.fetchone() if returning else None

    return _run(f)


def init_db() -> None:
    """スキーマとテーブルが無ければ作成する（既にあれば何もしない）。"""
    _execute(
        f"""
        create schema if not exists {SCHEMA};

        create table if not exists {SCHEMA}.pokemon (
            id bigint generated by default as identity primary key,
            species_name text not null,
            nickname text,
            level integer not null default 1,
            nature text,
            evolution_stage integer default 0,
            main_skill_name text,
            main_skill_level integer,
            ingredient_1 text,
            ingredient_2 text,
            ingredient_3 text,
            subskill_lv10 text,
            subskill_lv25 text,
            subskill_lv50 text,
            subskill_lv75 text,
            subskill_lv100 text,
            daifuku_rank text,
            daifuku_evals_json text,
            note text,
            created_at text not null default {_NOW_SQL},
            daifuku_eval_type integer,
            daifuku_eval_percent double precision,
            caught_level integer,
            current_level integer,
            last_eval_species_total double precision,
            last_eval_global_total double precision,
            last_eval_version text,
            last_eval_computed_at text,
            sleep_ribbon_stage integer default 0
        );

        create table if not exists {SCHEMA}.party (
            id bigint generated by default as identity primary key,
            name text not null,
            field_name text,
            recipe_categories text,
            candidate_recipes text,
            policy_tags text,
            member_ids text,
            note text,
            created_at text not null default {_NOW_SQL},
            updated_at text not null default {_NOW_SQL},
            random_field_berries text,
            role_targets text,
            event_bonuses text,
            main_recipe text
        );

        create table if not exists {SCHEMA}.user_settings (
            key text primary key,
            value_json text,
            updated_at text not null default {_NOW_SQL}
        );
        """
    )


def insert_pokemon(data: dict[str, Any]) -> int:
    """data のキーをそのままカラムに保存し、採番された id を返す。

    daifuku_evals_json は dict で渡してもよく、その場合は自動でJSON化する。
    """
    payload = dict(data)
    if isinstance(payload.get("daifuku_evals_json"), dict):
        payload["daifuku_evals_json"] = json.dumps(
            payload["daifuku_evals_json"], ensure_ascii=False
        )

    cols = ", ".join(payload.keys())
    placeholders = ", ".join(["%s"] * len(payload))
    sql = f"INSERT INTO pokemon ({cols}) VALUES ({placeholders}) RETURNING id"
    row = _execute(sql, tuple(payload.values()), returning=True)
    return row["id"]


def list_pokemon() -> list[dict[str, Any]]:
    return _fetchall("SELECT * FROM pokemon ORDER BY id DESC")


def delete_pokemon(pokemon_id: int) -> None:
    _execute("DELETE FROM pokemon WHERE id = %s", (pokemon_id,))


def get_setting(key: str, default: Any = None) -> Any:
    """user_settings から1件取得。値は JSON デコードして返す。未登録なら default。"""
    row = _fetchone("SELECT value_json FROM user_settings WHERE key = %s", (key,))
    if row is None:
        return default
    try:
        return json.loads(row["value_json"])
    except (TypeError, json.JSONDecodeError):
        return default


def set_setting(key: str, value: Any) -> None:
    """user_settings に1件 upsert。値は JSON エンコードして保存。"""
    payload = json.dumps(value, ensure_ascii=False)
    _execute(
        f"""
        INSERT INTO user_settings (key, value_json, updated_at)
        VALUES (%s, %s, {_NOW_SQL})
        ON CONFLICT (key) DO UPDATE SET
            value_json = excluded.value_json,
            updated_at = {_NOW_SQL}
        """,
        (key, payload),
    )


def get_all_settings() -> dict[str, Any]:
    """user_settings の全件を {key: 値} の辞書で返す。値は JSON デコード済み。"""
    out: dict[str, Any] = {}
    for r in _fetchall("SELECT key, value_json FROM user_settings"):
        try:
            out[r["key"]] = json.loads(r["value_json"])
        except (TypeError, json.JSONDecodeError):
            out[r["key"]] = None
    return out


def get_pokemon(pokemon_id: int) -> dict[str, Any] | None:
    return _fetchone("SELECT * FROM pokemon WHERE id = %s", (pokemon_id,))


def update_pokemon(pokemon_id: int, **fields: Any) -> None:
    """指定IDのポケモンレコードを部分更新する。fields のキーをそのままカラムに上書き。"""
    if not fields:
        return
    cols = ", ".join(f"{k} = %s" for k in fields.keys())
    sql = f"UPDATE pokemon SET {cols} WHERE id = %s"
    _execute(sql, (*fields.values(), pokemon_id))


# ---------- パーティ編成 ----------

_PARTY_JSON_LIST_FIELDS = (
    "recipe_categories",
    "candidate_recipes",
    "policy_tags",
    "member_ids",
    "random_field_berries",
    "event_bonuses",
)
_PARTY_JSON_DICT_FIELDS = (
    "role_targets",
)
_PARTY_JSON_FIELDS = _PARTY_JSON_LIST_FIELDS + _PARTY_JSON_DICT_FIELDS


def _serialize_party_payload(payload: dict[str, Any]) -> dict[str, Any]:
    out = dict(payload)
    for k in _PARTY_JSON_FIELDS:
        if k in out and not isinstance(out[k], str):
            default: Any = {} if k in _PARTY_JSON_DICT_FIELDS else []
            out[k] = json.dumps(out[k] or default, ensure_ascii=False)
    return out


def _deserialize_party_row(row: dict[str, Any] | None) -> dict[str, Any] | None:
    if row is None:
        return None
    d = dict(row)
    for k in _PARTY_JSON_FIELDS:
        default: Any = {} if k in _PARTY_JSON_DICT_FIELDS else []
        raw = d.get(k)
        try:
            d[k] = json.loads(raw) if raw else default
        except (TypeError, ValueError):
            d[k] = default
    return d


def insert_party(data: dict[str, Any]) -> int:
    payload = _serialize_party_payload(data)
    cols = ", ".join(payload.keys())
    placeholders = ", ".join(["%s"] * len(payload))
    sql = f"INSERT INTO party ({cols}) VALUES ({placeholders}) RETURNING id"
    row = _execute(sql, tuple(payload.values()), returning=True)
    return row["id"]


def update_party(party_id: int, **fields: Any) -> None:
    if not fields:
        return
    payload = _serialize_party_payload(fields)
    set_parts = [f"{k} = %s" for k in payload.keys()]
    set_parts.append(f"updated_at = {_NOW_SQL}")
    sql = f"UPDATE party SET {', '.join(set_parts)} WHERE id = %s"
    _execute(sql, (*payload.values(), party_id))


def list_parties() -> list[dict[str, Any]]:
    rows = _fetchall("SELECT * FROM party ORDER BY updated_at DESC, id DESC")
    return [_deserialize_party_row(r) for r in rows]


def get_party(party_id: int) -> dict[str, Any] | None:
    row = _fetchone("SELECT * FROM party WHERE id = %s", (party_id,))
    return _deserialize_party_row(row)


def delete_party(party_id: int) -> None:
    _execute("DELETE FROM party WHERE id = %s", (party_id,))


@lru_cache(maxsize=1)
def _load_master() -> dict[str, dict[str, Any]]:
    """data/pokemon_master.json を読み込み、種族名→レコードの辞書を返す。"""
    if not MASTER_PATH.exists():
        return {}
    raw = json.loads(MASTER_PATH.read_text(encoding="utf-8"))
    return {r["species_name"]: r for r in raw.get("records", [])}


def get_species_data(species_name: str) -> dict[str, Any] | None:
    """ポケモン名から種族固有データ（食材枠候補・主スキル等）を返す。

    マスターに見つからなければ None。
    返り値の構造は data/pokemon_master.json のレコードと同じ。
    """
    return _load_master().get(species_name)


def list_species_names() -> list[str]:
    """マスターに登録されている全種族名を図鑑順で返す。"""
    master = _load_master()
    return sorted(master.keys(), key=lambda n: master[n].get("dex_no", "9999"))


def list_all_master_records() -> list[dict[str, Any]]:
    """マスターの全レコードを図鑑番号順で返す。"""
    master = _load_master()
    return sorted(master.values(), key=lambda r: r.get("dex_no", "9999"))


@lru_cache(maxsize=1)
def _load_berry() -> list[dict[str, Any]]:
    """data/berry.json を読み込み、records のリストを返す。"""
    if not BERRY_PATH.exists():
        return []
    raw = json.loads(BERRY_PATH.read_text(encoding="utf-8"))
    return list(raw.get("records", []))


def list_all_berry_records() -> list[dict[str, Any]]:
    """きのみの全レコードを返す。並びはJSONの保存順（タイプ順）。"""
    return list(_load_berry())


@lru_cache(maxsize=1)
def _load_ingredient() -> list[dict[str, Any]]:
    """data/ingredient.json を読み込み、records のリストを返す。"""
    if not INGREDIENT_PATH.exists():
        return []
    raw = json.loads(INGREDIENT_PATH.read_text(encoding="utf-8"))
    return list(raw.get("records", []))


def list_all_ingredient_records() -> list[dict[str, Any]]:
    """食材の全レコードを返す。並びはJSONの保存順。"""
    return list(_load_ingredient())


@lru_cache(maxsize=1)
def _load_field() -> list[dict[str, Any]]:
    """data/field.json を読み込み、records のリストを返す。"""
    if not FIELD_PATH.exists():
        return []
    raw = json.loads(FIELD_PATH.read_text(encoding="utf-8"))
    return list(raw.get("records", []))


def list_all_field_records() -> list[dict[str, Any]]:
    """フィールドの全レコードを返す。並びは通常→EX、各内ではNo.順。"""
    return list(_load_field())


@lru_cache(maxsize=1)
def _load_recipe() -> list[dict[str, Any]]:
    """data/recipe.json を読み込み、records のリストを返す。"""
    if not RECIPE_PATH.exists():
        return []
    raw = json.loads(RECIPE_PATH.read_text(encoding="utf-8"))
    return list(raw.get("records", []))


def list_all_recipe_records() -> list[dict[str, Any]]:
    """レシピの全レコードを返す。並びはカテゴリ（カレー→サラダ→デザート）→No.順。"""
    return list(_load_recipe())


@lru_cache(maxsize=1)
def _load_main_skill() -> list[dict[str, Any]]:
    if not MAIN_SKILL_PATH.exists():
        return []
    raw = json.loads(MAIN_SKILL_PATH.read_text(encoding="utf-8"))
    return list(raw.get("records", []))


def list_all_main_skill_records() -> list[dict[str, Any]]:
    """メインスキルの全レコードを返す。並びは生テキスト記載順（≒分類順）。"""
    return list(_load_main_skill())


@lru_cache(maxsize=1)
def _load_subskill() -> list[dict[str, Any]]:
    if not SUBSKILL_PATH.exists():
        return []
    raw = json.loads(SUBSKILL_PATH.read_text(encoding="utf-8"))
    return list(raw.get("records", []))


def list_all_subskill_records() -> list[dict[str, Any]]:
    """サブスキルの全レコードを返す。並びは rarity（gold→blue→white）→記載順。"""
    return list(_load_subskill())


@lru_cache(maxsize=1)
def _load_evolution() -> list[dict[str, Any]]:
    """data/evolution.json を読み込み、records のリストを返す。"""
    if not EVOLUTION_PATH.exists():
        return []
    raw = json.loads(EVOLUTION_PATH.read_text(encoding="utf-8"))
    return list(raw.get("records", []))


def list_all_evolution_records() -> list[dict[str, Any]]:
    """進化系列の全レコードを返す。"""
    return list(_load_evolution())


def list_evolutions_from(species_name: str) -> list[dict[str, Any]]:
    """指定種族が進化できる先（複数あり得る）を返す。空なら進化先なし。"""
    return [r for r in _load_evolution() if r["from"] == species_name]


def list_evolutions_to(species_name: str) -> list[dict[str, Any]]:
    """指定種族の進化元（複数あり得る）を返す。空なら進化前なし。"""
    return [r for r in _load_evolution() if r["to"] == species_name]


@lru_cache(maxsize=1)
def _load_nature_raw() -> dict[str, Any]:
    """data/nature.json を読み込む（_meta も含む生データ）。"""
    if not NATURE_PATH.exists():
        return {"records": [], "_meta": {}}
    return json.loads(NATURE_PATH.read_text(encoding="utf-8"))


def list_all_nature_records() -> list[dict[str, Any]]:
    """性格の全レコードを返す。並びは生テキスト記載順（25種固定）。"""
    return list(_load_nature_raw().get("records", []))


def get_nature_modifiers() -> dict[str, dict[str, Any]]:
    """補正項目ごとの倍率（▲/▼）を返す。キー: speed/energy/ingredient/skill/exp。"""
    return dict(_load_nature_raw().get("_meta", {}).get("modifiers", {}))


def get_nature_record(name: str) -> dict[str, Any] | None:
    """性格名から1件取得。存在しない場合はNone。"""
    for r in _load_nature_raw().get("records", []):
        if r["name"] == name:
            return r
    return None


@lru_cache(maxsize=1)
def _load_evolution_item() -> list[dict[str, Any]]:
    """data/evolution_item.json を読み込み、records のリストを返す。"""
    if not EVOLUTION_ITEM_PATH.exists():
        return []
    raw = json.loads(EVOLUTION_ITEM_PATH.read_text(encoding="utf-8"))
    return list(raw.get("records", []))


def list_all_evolution_item_records() -> list[dict[str, Any]]:
    """進化アイテムの全レコードを返す。並びはJSONの保存順。"""
    return list(_load_evolution_item())


def list_evolutions_using_item(item_name: str) -> list[dict[str, Any]]:
    """指定の進化アイテムを使う進化レコードを evolution.json から検索する。"""
    results: list[dict[str, Any]] = []
    for r in _load_evolution():
        items = (r.get("conditions") or {}).get("items") or []
        if item_name in items:
            results.append(r)
    return results


@lru_cache(maxsize=1)
def _load_sleep_ribbon_raw() -> dict[str, Any]:
    """data/sleep_ribbon.json を読み込む（_meta も含む生データ）。"""
    if not SLEEP_RIBBON_PATH.exists():
        return {"records": [], "_meta": {}}
    return json.loads(SLEEP_RIBBON_PATH.read_text(encoding="utf-8"))


def list_all_sleep_ribbon_records() -> list[dict[str, Any]]:
    """おやすみリボンの全段階を返す。並びは stage 昇順。"""
    return list(_load_sleep_ribbon_raw().get("records", []))


def get_sleep_ribbon_record(stage: int) -> dict[str, Any] | None:
    """段階番号からリボンレコードを取得。stage=0 は「リボンなし」相当でNoneを返す。"""
    if stage <= 0:
        return None
    for r in _load_sleep_ribbon_raw().get("records", []):
        if r["stage"] == stage:
            return r
    return None
